name: Release

on:
  push:
    tags: ["v*"]

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

defaults:
  tools:
    bun: latest

jobs:
  precheck:
    name: Precheck
    type: custom
    runs_on: linux-medium
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Typecheck
        run: bun run typecheck
      - name: Lint
        run: bun run lint
      - name: Test
        run: bun run test

  build_ios:
    name: Build iOS
    needs: [precheck]
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    name: Submit to App Store
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: production
